set -g mouse on
setw -g mode-keys vi

# Colors & terminal behavior
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-256color:RGB,screen-256color:RGB,tmux-256color:RGB'
set -g xterm-keys on
set -g renumber-windows on

if-shell 'hostname -f 2>/dev/null | grep -Eq "\.hsn\.cm\.polaris\.alcf\.anl\.gov$"' 'set -g default-terminal "screen-256color"; set -g status off'

# Splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Copy-mode (vi)
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy 2>/dev/null || xclip -sel clip 2>/dev/null || wl-copy 2>/dev/null || cat >/dev/null"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.dotfiles/modules/tpm/tpm'
